name: Generate analytics
on:
  push:
    branches:
      - main
    paths: 
      - analytics-raw-data/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install packages
      run: python -m pip install pandas numpy urllib3 seaborn matplotlib

    - uses: yaananth/run-notebook@v1
      with:
        notebook: "analytics.ipynb"

    - name: Commit Metrics SonarCloud File
      run: |
            git config --global user.email "${{ secrets.USER_EMAIL }}"
            git config --global user.name "${{ secrets.USER_USERNAME }}"
            git commit -m "Gerando analise de metricas"
            git add .
            git push
            echo "Metrics analysis generated successfully."